### ISSUE TITLE
error when yoiking the nordish folder.

### ISSUE THREAD

**Issue by GustavoPrietoP** [MrJakeSir/dots#1]
i get this error `attempt: to call a nil value (field 'at_screen_connect')`

this is what i have in my `rc.lua`

`awful.screen.connect_for_each_screen(function(s) beautiful.at_screen_connect(s) end)
`

**Comment by MrJakeSir** [comment]
Hello! thats a very weird bug, i recommend you to **not** clone the dotfiles because it could throw a random error like that, sorry for the inconvenience man

**Comment by GustavoPrietoP** [comment]
i'll try to find a fix for it, no worries tho :)

great rice btw ;)
