### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Rickshawala** [MrJakeSir/dots#3]
![ksnip_20210917-205100](https://user-images.githubusercontent.com/81474331/133807945-3a249ac8-b4ba-4413-b1ae-2d0ca5a1b483.png)

**Comment by MrJakeSir** [comment]
Thank you! this is very useful, can you try again? i think i fixed that error

**Comment by Rickshawala** [comment]
Yes it works again. Thank you very much this looks beautiful

**Comment by MrJakeSir** [comment]
Happy to hear that! sorry if the code is a mess, you can change the colors in awesome/utils/colors.lua, all the bar configuration is in themes/nordish/theme.lua and if you want to change your avatar in the menu, change [this line to the path of your image](https://github.com/MrJakeSir/dots/blob/f3b98bcee9243b2fefe509dbd20b5dfd0a9aeeff/awesome/widgets/menu.lua#L14)
