### ISSUE TITLE
errors in icons

### ISSUE THREAD

**Issue by has12zen** [MrJakeSir/dots#4]
I really liked your theme but was having issues in getting all icons, How can one install all required icons?
also there seems to be a lag/slowness in the theme can it be configured somewhere?
and lastly when the main window(start button/awesome svg)  is open and I click on backdrop it does not close it but if I click on main window it closes regardless I click on  any icon within the window or not where can i configure this backdrop behaviour?
Thx for this awesome rice

**Comment by MrJakeSir** [comment]
[you need this nerd font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Bold/complete/JetBrains%20Mono%20Bold%20Nerd%20Font%20Complete.ttf), just download the ttf file and move it into ~/.fonts, also, the menu will automatically close when clicked but i will fix it

**Comment by MrJakeSir** [comment]
also, what do you mean by lag/slowness in the theme?

**Comment by has12zen** [comment]
lag slowness may be due to fade in effect i think

**Comment by MrJakeSir** [comment]
> lag slowness may be due to fade in effect i think

that's because of picom, you can disable it in the conf

**Comment by MrJakeSir** [comment]
> lag slowness may be due to fade in effect i think
You can use [my picom conf](https://github.com/MrJakeSir/dots/tree/master/picom)

**Comment by has12zen** [comment]
ohh ok thanks!
the picom refresh rate was 0 it was a bit slow for me :sweat_smile:

**Comment by MrJakeSir** [comment]
> ohh ok thanks!
> the picom refresh rate was 0 it was a bit slow for me

ok so i can close the issue?

**Comment by has12zen** [comment]
yep
