### ISSUE TITLE
font error

### ISSUE THREAD

**Issue by iluvgirlswithglasses** [MrJakeSir/dots#5]
Sorry if I'm stupid but how can I fix this font error:
https://raw.githubusercontent.com/iluvgirlswithglasses/ImgHost/main/screenshot/arch/fonterror.png

I just need a hint. Thanks.

**Comment by iluvgirlswithglasses** [comment]
addition: I copied the whole `./awesome/` folder from your repository to `~/.config/awesome`, including `awesome-buttons` and `awesome-wm-widgets`

**Comment by MrJakeSir** [comment]
![image](https://user-images.githubusercontent.com/81118866/133912999-88c31dab-e820-4d4a-8bda-045242584903.png)
as i said in the readme.md, you need that nerd font! that will fix the issue, download the nerd font from the  link of the readme.md and move it to your ~/.fonts, then reboot and you will bee ok
