### ISSUE TITLE
Error while trying to use theme 1

### ISSUE THREAD

**Issue by rhearmas** [MrJakeSir/dots#6]
Quite simply the title. When setting the theme in `~/.config/awesome/rc.lua` to **1**, reloading Awesome gives us a fantastic error:

```
error: /home/rhearmas/.config/awesome/rc.lua:265: attempt to call a nil value (field 'at_screen_connect')
```

Please note that Awesome spits out two error windows in the corner; I've truncated the messages and the block above is only the first error window, but there's really no need to include everything else since it's just the full stack of files it spits out in the second window.

This never happens when using theme **2**, which is the default theme when cloning the repo. Normally it would work just fine, but it seems like it doesn't want to behave normally.

**Comment by MrJakeSir** [comment]
forgot to remove the theme two, the theme two have a lot of problems, you shouldn't use it
