### ISSUE TITLE
Hey! Why is this closed-source?

### ISSUE THREAD

**Issue by YeetusBaboon** [MrJakeSir/dots#8]
I love your setup, and would love to use parts of it for myself. I don't want to question your decision, I'm simply curious as to why it's closed-source (after all, why not just delete the repository if you wanted it gone?) Plus, you can still view certain files with commit history. 

Thanks.

**Comment by MrJakeSir** [comment]
yes, you can still see commit history, i will rewrite the dotfiles, thats why i made the closed source joke

**Comment by YeetusBaboon** [comment]
Oh, alright.
